services:
  db:
    image: postgres:17.1
    container_name: postgres
    environment:
      POSTGRES_USER: akadoshin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: task_manager_db
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db